"""
PyMOL script generator for AF3 interface analysis.

Generates .py files that can be run inside PyMOL to visualize
predicted interfaces with PAE-based confidence coloring.
"""

from pathlib import Path
from typing import Dict, List, Optional, Tuple


def generate_pymol_script(
    cif_path: str,
    prediction_name: str,
    chain_a_id: str,
    chain_b_id: str,
    protein_a_name: str,
    protein_b_name: str,
    interface_residues: Optional[Dict[str, List[Tuple[int, float]]]] = None,
    contacts: Optional[List[Dict]] = None,
    seed: int = 0,
    sample: int = 0,
) -> str:
    """
    Generate a PyMOL .py script for interface visualization.

    Args:
        cif_path: Absolute path to the CIF file
        prediction_name: e.g. "a0avf1_and_o15182"
        chain_a_id, chain_b_id: Chain identifiers
        protein_a_name, protein_b_name: Display names (gene names or accessions)
        interface_residues: From compute_interface_pae_per_residue()
        contacts: From analyze_interface() — list of contact dicts
        seed, sample: Model identifiers
    """
    # Categorize interface residues by PAE tier
    tiers = {'very_high': [], 'high': [], 'moderate': [], 'low': []}
    tier_map = {}  # chain -> {res_num: tier}

    if interface_residues:
        for chain_id, res_list in interface_residues.items():
            tier_map[chain_id] = {}
            for res_num, pae_val in res_list:
                if pae_val < 3.0:
                    tier = 'very_high'
                elif pae_val < 5.0:
                    tier = 'high'
                elif pae_val < 8.0:
                    tier = 'moderate'
                else:
                    tier = 'low'
                tiers[tier].append((chain_id, res_num, pae_val))
                tier_map[chain_id][res_num] = tier

    # Build residue selections per tier per chain
    def _resi_sel(chain, residues):
        if not residues:
            return None
        resi_str = "+".join(str(r) for r in sorted(residues))
        return f"chain {chain} and resi {resi_str}"

    # Group by chain + tier
    chain_tier_residues = {}
    for tier_name, entries in tiers.items():
        for chain_id, res_num, _ in entries:
            key = (chain_id, tier_name)
            if key not in chain_tier_residues:
                chain_tier_residues[key] = []
            chain_tier_residues[key].append(res_num)

    # All interface residues per chain
    interface_a = sorted(set(r for r, _ in interface_residues.get(chain_a_id, []))) if interface_residues else []
    interface_b = sorted(set(r for r, _ in interface_residues.get(chain_b_id, []))) if interface_residues else []

    # Hub residues from contacts (residues with >= 3 contacts)
    hub_a_residues = []
    hub_b_residues = []
    if contacts:
        from collections import Counter
        count_a = Counter()
        count_b = Counter()
        for c in contacts:
            count_a[c.get('chain_a_res', 0)] += 1
            count_b[c.get('chain_b_res', 0)] += 1
        hub_a_residues = sorted([r for r, n in count_a.items() if n >= 3])
        hub_b_residues = sorted([r for r, n in count_b.items() if n >= 3])

    # Build the script
    script = f'''"""
PyMOL Interface Visualization Script
=====================================
Prediction: {prediction_name}
Model: seed-{seed}_sample-{sample}
{protein_a_name} (chain {chain_a_id}) vs {protein_b_name} (chain {chain_b_id})

Generated by AF3 Analysis App

Usage:
  In PyMOL: run {prediction_name}_pymol.py
  Or: File -> Run Script -> select this file
"""

from pymol import cmd, stored

# ── Configuration ──────────────────────────────────────────────────────
CIF_FILE = r"{cif_path}"
CHAIN_A = "{chain_a_id}"
CHAIN_B = "{chain_b_id}"
NAME_A = "{protein_a_name}"
NAME_B = "{protein_b_name}"

# ── Load structure ─────────────────────────────────────────────────────
cmd.load(CIF_FILE, "{prediction_name}")
cmd.remove("solvent")

# ── Base styling ───────────────────────────────────────────────────────
cmd.bg_color("white")
cmd.hide("everything")
cmd.show("cartoon")
cmd.set("cartoon_fancy_helices", 1)
cmd.set("cartoon_smooth_loops", 1)

# Chain colors
cmd.color("lightblue", f"chain {{CHAIN_A}}")
cmd.color("lightorange", f"chain {{CHAIN_B}}")

# ── Interface residue selections ───────────────────────────────────────
'''

    # Add interface selections
    if interface_a:
        sel = "+".join(str(r) for r in interface_a)
        script += f'cmd.select("interface_{protein_a_name}", f"chain {{CHAIN_A}} and resi {sel}")\n'
    if interface_b:
        sel = "+".join(str(r) for r in interface_b)
        script += f'cmd.select("interface_{protein_b_name}", f"chain {{CHAIN_B}} and resi {sel}")\n'

    if interface_a or interface_b:
        parts = []
        if interface_a:
            parts.append(f"interface_{protein_a_name}")
        if interface_b:
            parts.append(f"interface_{protein_b_name}")
        script += f'cmd.select("interface_all", "{" or ".join(parts)}")\n'

    # PAE-tier selections and coloring
    script += '''
# ── PAE confidence coloring ────────────────────────────────────────────
# Green tones = high confidence, warm tones = lower confidence
'''

    tier_colors = {
        'very_high': ('forest', 'PAE < 3 A'),
        'high': ('green', 'PAE 3-5 A'),
        'moderate': ('yellow', 'PAE 5-8 A'),
        'low': ('orange', 'PAE 8-12 A'),
    }

    for (chain_id, tier_name), residues in sorted(chain_tier_residues.items()):
        color, desc = tier_colors[tier_name]
        sel = "+".join(str(r) for r in sorted(residues))
        chain_label = protein_a_name if chain_id == chain_a_id else protein_b_name
        sel_name = f"pae_{tier_name}_{chain_label}"
        script += f'cmd.select("{sel_name}", f"chain {chain_id} and resi {sel}")\n'
        script += f'cmd.color("{color}", "{sel_name}")  # {desc}\n'

    # Show interface as sticks
    script += '''
# ── Show interface residues as sticks ──────────────────────────────────
cmd.show("sticks", "interface_all")
cmd.set("stick_radius", 0.15, "interface_all")
'''

    # Hub residues
    if hub_a_residues or hub_b_residues:
        script += '\n# ── Hub residues (>= 3 contacts) ──────────────────────────────────────\n'
        if hub_a_residues:
            sel = "+".join(str(r) for r in hub_a_residues)
            script += f'cmd.select("hubs_{protein_a_name}", f"chain {{CHAIN_A}} and resi {sel}")\n'
            script += f'cmd.show("spheres", f"hubs_{protein_a_name} and name CA")\n'
            script += f'cmd.set("sphere_scale", 0.6, f"hubs_{protein_a_name}")\n'
        if hub_b_residues:
            sel = "+".join(str(r) for r in hub_b_residues)
            script += f'cmd.select("hubs_{protein_b_name}", f"chain {{CHAIN_B}} and resi {sel}")\n'
            script += f'cmd.show("spheres", f"hubs_{protein_b_name} and name CA")\n'
            script += f'cmd.set("sphere_scale", 0.6, f"hubs_{protein_b_name}")\n'

    # Convenience functions
    script += f'''
# ── Convenience functions ──────────────────────────────────────────────
def show_interface():
    """Zoom to interface region"""
    cmd.zoom("interface_all", buffer=10)
    print("Zoomed to interface")

def show_chain_a():
    """Focus on {protein_a_name}"""
    cmd.zoom(f"chain {{CHAIN_A}}", buffer=5)

def show_chain_b():
    """Focus on {protein_b_name}"""
    cmd.zoom(f"chain {{CHAIN_B}}", buffer=5)

def show_pae_only():
    """Show only PAE-colored interface, hide sticks"""
    cmd.hide("sticks")
    cmd.hide("spheres")
    cmd.show("cartoon")
    cmd.zoom("interface_all", buffer=10)

def show_contacts():
    """Show interface sticks and hub spheres"""
    cmd.show("sticks", "interface_all")
    cmd.show("spheres", "hubs_{protein_a_name} and name CA")
    cmd.show("spheres", "hubs_{protein_b_name} and name CA")
    cmd.zoom("interface_all", buffer=10)

cmd.extend("show_interface", show_interface)
cmd.extend("show_chain_a", show_chain_a)
cmd.extend("show_chain_b", show_chain_b)
cmd.extend("show_pae_only", show_pae_only)
cmd.extend("show_contacts", show_contacts)

# ── Final setup ────────────────────────────────────────────────────────
cmd.deselect()
cmd.zoom("interface_all", buffer=12)
cmd.set("ray_shadow", 0)
cmd.set("specular", 0.2)

print("\\n" + "="*60)
print(f"  {{NAME_A}} (chain {{CHAIN_A}}) vs {{NAME_B}} (chain {{CHAIN_B}})")
print(f"  Interface residues: {{NAME_A}}={len(interface_a)}, {{NAME_B}}={len(interface_b)}")
print("="*60)
print("Commands: show_interface, show_chain_a, show_chain_b,")
print("          show_pae_only, show_contacts")
print("="*60 + "\\n")
'''

    return script
